# Generated by Django 5.2.15 on 2026-07-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('full_text', models.TextField(blank=True, verbose_name='Полный текст')),
                ('url', models.CharField(max_length=500, unique=True, verbose_name='URL')),
                ('source', models.CharField(max_length=100, verbose_name='Источник')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Категория')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
            },
        ),
    ]
