# Generated by Django 5.2.15 on 2026-07-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Доход')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма налога')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка налога')),
                ('status', models.CharField(max_length=30, verbose_name='Статус')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Расчет налога',
                'verbose_name_plural': 'Расчеты налогов',
                'ordering': ['-created_at'],
            },
        ),
    ]
