# Generated by Django 5.2.15 on 2026-07-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('intent', models.CharField(blank=True, max_length=50, verbose_name='Интент')),
                ('confidence', models.FloatField(default=0, verbose_name='Уверенность')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Токенов использовано')),
                ('response_time', models.FloatField(default=0, verbose_name='Время ответа (сек)')),
                ('is_helpful', models.BooleanField(blank=True, null=True, verbose_name='Помогло?')),
                ('context', models.JSONField(default=dict, verbose_name='Контекст')),
                ('meta', models.JSONField(default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'История чата',
                'verbose_name_plural': 'Истории чатов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('predicted_intent', models.CharField(choices=[('tax', 'Налоги'), ('documents', 'Документы'), ('payments', 'Выплаты'), ('support', 'Поддержка'), ('general', 'Общий'), ('unknown', 'Неизвестный')], max_length=20, verbose_name='Предсказанный интент')),
                ('confidence', models.FloatField(verbose_name='Уверенность')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Верный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог интента',
                'verbose_name_plural': 'Логи интентов',
            },
        ),
    ]
