# Generated by Django 5.2.15 on 2026-07-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('doc_type', models.CharField(choices=[('report', 'Отчет'), ('certificate', 'Справка'), ('contract', 'Договор'), ('invoice', 'Счет')], max_length=20, verbose_name='Тип')),
                ('content', models.JSONField(default=dict, verbose_name='Содержание')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к файлу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
